[package]
name = "tauri-plugin-escpos"
version = "0.0.0"
authors = ["lnxdxtf"]
description = ""
edition = "2021"
rust-version = "1.70"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-escpos"

[dependencies]
tauri = { version = "2.0.0-beta.22" }
serde = "1.0"
thiserror = "1.0"
eco_print = { git = "https://github.com/lnxdxtf/eco_print.git", branch = "main" }

[build-dependencies]
tauri-plugin = { version = "2.0.0-beta.17", features = ["build"] }
