"$schema" = "schemas/schema.json"
[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-request-permissions",
    "allow-permissions-status",
    "allow-start",
    "allow-start-scan",
    "allow-connect",
    "allow-disconnect",
]
