"$schema" = "schemas/schema.json"
[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-request-permissions",
    "allow-permissions-ok",
    "allow-start",
    "allow-check-store-state",
]
